### PR TITLE
More rendering improvements

### LINKED ISSUE #1044: Support letter spacing
Related: https://github.com/Microsoft/vscode/issues/35695

### PR DESCRIPTION
**Pull request by Tyriar**
- Adds `letterSpacing` option
- Rows are now clipped for uncached draws using the *cell* height, not the *char* height. This means that larger characters when not drawn from the char atlas will consume the additional space provided by the `lineHeight`

Fixes #1044

### CODE REVIEW

**Comment by mofux** [comment]
@Tyriar Does this fix #1044 by manually setting the new `letterSpacing` option?

**Comment by Tyriar** [comment]
It fixes #1044 as that's just a feature for letterSpacing, it provides a workaround for https://github.com/Microsoft/vscode/issues/35695 for the time being. The reason they don't use "standard spacing" is so they align with the grid such that the charatlas can be utilized. Using the charatlas on floating point numbers looks OK, but not perfect.

**Comment by Tyriar** [comment]
Ping

**Comment by mofux** [comment]
LGTM 👍

**Pull request merged**
