### PR TITLE
Fixed selection issue when terminal is in nested scrolled elements

### PR DESCRIPTION
**Pull request by dcylabs**
Hello, 
Had an issue with text selection when the terminal was in nested scrolled elements, fixed the problem by looping each parent element and adding scroll value to coordinates.

### CODE REVIEW

**Comment by Tyriar** [comment]
Can you provide a small example that demonstrates the bug this fixes?

**Comment by dcylabs** [comment]
Here is the short example, if you dont scroll down, selection works well on the first lines, if you scroll, the selection is not right : https://embed.plnkr.co/xkQtCBW8v5rDCLhiMtdy/

**Comment by dcylabs** [comment]
Pushing again, my code solved my case, but broke with body scrolling, now solved by not adding scrollTop of body to coordinates.

**Comment by cancan101** [comment]
Ping on get this merged?

**Comment by mofux** [comment]
The xterm maintainer team is quite busy for the next two weeks. We've not forgotten this contribution 🤞, but please allow us some time to review and test it carefully before it gets merged

**Comment by Tyriar** [comment]
I merged v3 in and resolved the conflicts.

**Comment by Tyriar** [comment]
Thanks for this, seems to work great in both the demo and vscode :+1: 

Sorry about the delay, been super busy :smile:

**Comment by cancan101** [comment]
any chance to get this backported to the 2x branch?

**Comment by Tyriar** [comment]
@cancan101 I'll leave that up to @parisk

**Comment by cancan101** [comment]
@parisk ?

**Comment by parisk** [comment]
@cancan101 we do not plan to backport this to 2.9 now.

Xterm.js 3.0 will land in exactly one month, so we are focusing completely on it. Is there anything blocking you from using the `v3` branch?

**Comment by cancan101** [comment]
I am more interested in getting a release of xterm.js (version number less relevant) in order to fix the issue in jupyter: https://github.com/jupyter/notebook/issues/2850

**Comment by parisk** [comment]
6 November is the release date for `v3`, so you can count on that.

**Comment by cancan101** [comment]
@parisk any updates on the V3 release?

**Pull request merged**
