### PR TITLE
Replace Linkifier RegExp to RFC3986 based one

### PR DESCRIPTION
**Pull request by tmyt**
Current Linkifier has some problems.
The PR replace Linkifier RegExp to RFC3986 based one, and aim to resolve issues #599 and #601.

These URLs are now Linkify.

- http://example.enterprises/
- http://[::1]/
- ftp://example.com/
- chrome-devtools://devtools/
- mailto:xxx@example.com
- about:blank

Could you discuss "should" or "should not" linkify the URI without "//"?

### CODE REVIEW

**Comment by tmyt** [comment]
The code wrote myself with refer the Appendix A of [IETF RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) documentation.

Strictly, Unicode characters is not allowed in URI and should be encode with Percent or Punycode. Then this implementation does not support Unicode chars.

**Comment by Tyriar** [comment]
@tmyt strictly, same with brackets which get encoded. Browsers and such will try to help the user out by allowing unencoding characters in URLs, there are also legal unicode domain names now. I wonder if doing this is even worth it as the real fix imo is to implement a proper parser to get the ideal behavior as in https://github.com/sourcelair/xterm.js/issues/583

**Comment by tmyt** [comment]
@Tyriar Ah, I could not check #583 that implement in mean time, the PR is not needed. If not needed, please reject this.

**Comment by Tyriar** [comment]
@tmyt while this would be an improvement, it's probably a good idea to not switch to this and then a parser. Thanks for understanding :smiley: something like this is what I'm thinking for the parser https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/linkComputer.ts

**Pull request closed without merging**
