### PR TITLE
Retain wrapped line state when copying

### LINKED ISSUE #443: Copying a wrapped line results in a newline at the end of the wrapped line
Copying and pasting a wrapped line, introduces a newline character at the position the line was wrapped.

### Steps to reproduce

1. Open the demo
2. Paste a long `echo` line, like the one below:
    ```
    echo this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big
    ```
3. When copied, the resulting line should be:
    ```
    this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big
    ```
4. It actually is:
    ```
    this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-
    is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big
    ```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #443

### CODE REVIEW

**Comment by Tyriar** [comment]
I created https://github.com/sourcelair/xterm.js/issues/695 to follow up the `isWrapped` property on an array situation. Should be fine for the time being, it's mainly just an issue when we move the buffer to TS.

**Comment by cancan101** [comment]
Any chance of getting a minor release with this change?

**Comment by Tyriar** [comment]
Ping @parisk

**Comment by parisk** [comment]
Since this is the last week of June, let's hold on until next Monday. I can make an early release for 2.8 on Monday for sure.

**Comment by marcosnils** [comment]
@Tyriar @parisk I've updated PWD (http://play-with-docker.com) with this release but it seems that for some reason I'm still getting \n when copying and pasting long lines. Is there something I'm missing?

**Comment by Tyriar** [comment]
@marcosnils what command are you running? The program may be formatting based on the width of the terminal? It's also worth verifying whether copying works fine on Terminal.app/gnome-terminal/etc.

A new issue with more details would be great 😃

**Comment by marcosnils** [comment]
@Tyriar if you go to PWD, type `echo asdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdasasdsadasdasdasdasdas`  and copy / paste that results you'll see that xterm adds newline when it wraps the text. If you try the same thing in gnome-terminal this doesn't happen.

**Comment by Tyriar** [comment]
@marcosnils hmm, same thing works fine in VS Code using the new changes. Debugging PWD, it looks like `bufferLine.isWrapped` is not set for the wrapped line in `SelectionManager.selectionText`.

**Comment by Tyriar** [comment]
I can reproduce the issue on master, however it doesn't occur in my vscode-release/1.14 branch which explains why it's working in VS Code.

**Comment by Tyriar** [comment]
Ok I can't seem to reproduce in master anymore 😕

**Comment by Tyriar** [comment]
Repro steps are flaky, copying from PWD just worked fine:

screen shot 2017-07-07 at 11 03 14 am

**Comment by Tyriar** [comment]
I know what's happening... Wrapped line status isn't being recorded correctly for the initial viewport that the terminal was initialized with (the first 24 rows). Get beyond this point and it works fine.

**Comment by Tyriar** [comment]
@marcosnils it would be handy to be able to add sessions without needing to resize the window 😄 

screen shot 2017-07-07 at 11 06 10 am

**Comment by Tyriar** [comment]
@marcosnils also selection seems not to be aligned with the cursor in your app, I'm guessing this is related to your CSS or something as it works fine in the demo and VS Code.

**Comment by Tyriar** [comment]
Moved to issue #767, PR out in https://github.com/sourcelair/xterm.js/pull/768

**Comment by marcosnils** [comment]
> @marcosnils also selection seems not to be aligned with the cursor in your app, I'm guessing this is related to your CSS or something as it works fine in the demo and VS Code

thx for reporting this and providing a fix so quickly. Do you think it'll take long to be merged?. So I don't have to merge manually :)

**Comment by Tyriar** [comment]
@marcosnils thanks for reporting so quickly 😄 

@parisk normally does the publishing to npm, unless other issues come in I'd say we should publish this with 2.8.1 as soon as he's free. Might need to wait until Sunday night/Monday due to it being the weekend over there.

**Comment by marcosnils** [comment]
@Tyriar thx. I was referring to merge to master. I can build from there and deploy manually. PWD is not using npm actually :fearful:

**Comment by Tyriar** [comment]
@marcosnils you could probably point at https://github.com/Tyriar/xterm.js/tree/767_initial_viewport_wrap in the meantime then. If you're using a custom npm dep this is how you point at a branch: https://github.com/Microsoft/vscode/blob/b32d2d44902eafbbdc252f0260cdbd938a5686f8/package.json#L46

**Pull request merged**
