### PR TITLE
Add IP addresses to linkify

### LINKED ISSUE #91: The linkify addon doesn't linkify IP addresses
image

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #91 

---

image

The fact that the invalid port IP address is still matched is to do with the current `negatedPathCharacterSet`, it will linkify `:http://www.google.com:` too.

### CODE REVIEW

**Comment by akalipetis** [comment]
Shall we put the port clause after either host, or IP? This would make more sense IMO.

Thanks for the contribution 🎆

**Comment by Tyriar** [comment]
@akalipetis done

**Comment by Tyriar** [comment]
+tests

**Comment by akalipetis** [comment]
LGTM, thanks a lot!

**Pull request merged**
