### PR TITLE
Fix exception when increasing size when viewport is at top of buffer

### LINKED ISSUE #154: Exception when increasing terminal vertical size when at the top of the buffer
1. Open the terminal
2. Fill terminal with output beyond the number of rows
4. Scroll to the very top
5. Increase number of rows via `resize`

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at Terminal.refresh (/home/daniel/dev/Microsoft/vscode/node_modules/xterm/src/xterm.js:1240:24)
    at /home/daniel/dev/Microsoft/vscode/node_modules/xterm/src/xterm.js:1217:18
```

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #154

### CODE REVIEW

**Comment by parisk** [comment]
When I am reproducing the steps described at #154, while having checked out this branch I get the following error message:

```
xterm.js:1275 Uncaught TypeError: Cannot read property '0' of undefinedTerminal.refresh @ xterm.js:1275(anonymous function) @ xterm.js:1222
```

## Screenshot
image

**Comment by Tyriar** [comment]
@parisk that's the original error, are you sure you're in the `154_fix_resize_at_top_exception` branch and not `master`?

**Comment by Tyriar** [comment]
Ping @parisk, please look at this again asap if you can, pretty sure you saw the original error that the commit fixes.

**Comment by parisk** [comment]
Sorry for delaying on this @Tyriar. Yes, this seems to be happening on the correct branch for me.

Also according to #154 the initial error is:

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at Terminal.refresh (/home/daniel/dev/Microsoft/vscode/node_modules/xterm/src/xterm.js:1240:24)
    at /home/daniel/dev/Microsoft/vscode/node_modules/xterm/src/xterm.js:1217:18
```

The current error is

```
xterm.js:1275 Uncaught TypeError: Cannot read property '0' of undefined
Terminal.refresh @ xterm.js:1275
(anonymous function) @ xterm.js:1222
```

## Screenshot
image

**Comment by Tyriar** [comment]
@parisk ah, I think I saw this one while fixing the issue. I'll check it out.

**Comment by Tyriar** [comment]
Fixed, I guess I did a bad refactor before commiting :confused:

**Comment by parisk** [comment]
Works great. Thanks!

**Pull request merged**
