### PR TITLE
Disable onScroll event during application mode

### LINKED ISSUE #235: Entering application mode with a large buffer will scroll to the top of the buffer temporarily
This is happening due to the reduction of the scroll bar when entering application mode but the scrollTop event is still going off.

See https://github.com/Microsoft/vscode/issues/10685 for original report.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #235

### CODE REVIEW

**Comment by ayapi** [comment]
@Tyriar ,
related to that i mentioned on #151, i think, to begin with, we shouldn't freeze scrolling on the viewport.
because, on original XTerm, even if it entered to application mode, we can scroll by <kbd>shift+pageup</kbd> and <kbd>shift+pagedown</kbd>

**Comment by Tyriar** [comment]
@ayapi scrolling using the scroll bar already is disabled, this just prevents a weird bug where it scrolls to top when entering an app. Mouse wheel events should probably be passed to the application rather than handled by the scroll bar during application mode (which they aren't doing currently), for example to scroll the cursor in vim.

**Comment by ayapi** [comment]
@Tyriar thank you, i think maybe i get it.

**Comment by parisk** [comment]
Works great! LGTM 👍 .

**Pull request merged**
