### PR TITLE
WIP: Introduce Lines class for terminal line management

### PR DESCRIPTION
**Pull request by parisk**

### CODE REVIEW

**Comment by parisk** [comment]
@Tyriar would love to hear your thoughts on something like that.

**Comment by Tyriar** [comment]
@parisk I already do most of this in my WIP branch for #361 https://github.com/Tyriar/xterm.js/blob/361_circular_list_scrollback/src/utils/CircularList.ts which is nearly done, would prefer to wait for that one.

**Comment by parisk** [comment]
👍 , I propose closing this down then and waiting to merge your branch before we move forward with #404, in order to leverage the circular list there. What do you think?

**Comment by Tyriar** [comment]
Yeah sounds good :smiley:

**Pull request closed without merging**
