### PR TITLE
Add statement on browser support

### LINKED ISSUE #183: State official browser support in README
Recommended for v1.0 milestone, here's what the sourcelair documentation says:

- Chrome	48+
- Firefox	44+
- Safari	8+
- Internet Explorer	11+
- Opera	35+

Having this will also make it easier in the future to tell why a particular version is required as you can check the commit in which they were bumped.

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #183 

---

These can be tweaked as necessary later.

### CODE REVIEW

**Comment by parisk** [comment]
Great, thanks! Should we mention Edge as well, or is it considered part of Internet Explorer?

One non-blocking question also; are there any specific features that make xterm.js incompatible with IE <11, Chrome <48, etc.? If yes, does it make any sense to refer them?

**Comment by Tyriar** [comment]
Yes I'll add Edge.

Potentially, it might be good to just state a baseline and adjust it accordingly though. Not sure I'll have time to investigate whether it works in the older browsers.

**Comment by parisk** [comment]
> Potentially, it might be good to just state a baseline and adjust it accordingly though

👍  definitely. Let's add Edge and merge this!

**Comment by parisk** [comment]
Thanks a lot @Tyriar!

**Pull request merged**
