### PR TITLE
Add linkify addon to demo

### PR DESCRIPTION
**Pull request by Tyriar**

### CODE REVIEW

**Comment by parisk** [comment]
The linkify addon has some major issues right now (#27, #24) which should be fixed before adding it to the demo.

Will try to deal with linkify, after dealing with CJK characters.

**Comment by Tyriar** [comment]
I wouldn't consider #24 a blocker though, seems like a harmless limitation. It would be a great enhancement to support only single-line URLs imo. #27 and #96 block adoption in vscode from what I can see so far.

**Comment by parisk** [comment]
#27 is the big blocker actually. I hope that I will be able to deal with this, along with https://github.com/sourcelair/xterm.js/issues/96#issuecomment-225559809 within tomorrow.

**Comment by Tyriar** [comment]
Closing this off, it's trivial to do if we want.

**Pull request closed without merging**
