### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saswatds**
Adding a getting started instruction for adding xterm to a parent div and listening for data output from xterm

### CODE REVIEW

**Comment by parisk** [comment]
Thanks your contribution @saswatds! I think the best thing would be shaping this based on the **Quick start** section at http://xtermjs.org/, which provides also a more complete example.

Do you believe you can refactor this accordingly?

**Comment by Tyriar** [comment]
Here's the repo: https://github.com/xtermjs/xtermjs.org/

**Comment by saswatds** [comment]
Yeah sure.. I am on.

**Comment by parisk** [comment]
Thanks a lot for this @saswatds!

**Pull request merged**
