### PR TITLE
Fix issue with small scrollback value

### LINKED ISSUE #506: Prevent scrollback from being less than the terminal's row count
Downstream issue: https://github.com/Microsoft/vscode/issues/19193

Setting a scrollback smaller than the row count causes unexpected results since our scrollback is not the *actual* scrollback but the size of the buffer.

### PR DESCRIPTION
**Pull request by irokas**
Closes #506

### CODE REVIEW

**Comment by Tyriar** [comment]
I think we also need to cover the case where scrollback is the minimum and then the number of rows increases.

**Comment by parisk** [comment]
Is it OK, if we

1. reject increasing the number of rows above the current `scrollback` value
2. return `false`
3. print a similar warning message

**Comment by Tyriar** [comment]
Either that or setting to the scrollback to max(currentScrollback, rows)

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/750

**Pull request merged**
