### PR TITLE
Fix some tests and docs.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
Fix some tests and docs. Merge to the master.
Target branch: buffer-set.

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
@parisk review please.

**Comment by parisk** [comment]
@AndrienkoAleksandr can you please rebase with the updated `buffer-set` branch?

**Comment by AndrienkoAleksandr** [comment]
ok, I will rebase.

**Comment by AndrienkoAleksandr** [comment]
done, @parisk.

**Comment by AndrienkoAleksandr** [comment]
We need to fix one more test escape-sequences-test.js ...

**Pull request merged**
