### PR TITLE
Require ctrl for link clicks

### LINKED ISSUE #578: Change terminal links to require ctrl
I think we should change the link behavior to require ctrl+click for the following reasons:

- This is how most terminal emulators work
- Users can accidentally open links when they want to focus the terminal or select text
- It could mess with terminal applications

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #578

### CODE REVIEW

**Comment by mofux** [comment]
I actually quite like the way cloud9 does it [https://github.com/c9/core](https://github.com/c9/core):

If you hover a resolved link, it will get underlined and you get a cursor: pointer, and on left click they will show a context menu that allows you to interact with the file. Adding the context menu should be handled by the implementor, but it would be awesome if we could listen to link clicked events, e.g.:

```javascript

term.on('link-open', (evt, uri) => {

  // only continue if the ctrl key was held
  if (!evt.ctrlKey) return evt.preventDefault();

  // show context menu for this uri
  ...

});

```

screen shot 2017-03-03 at 12 38 29

**Comment by mofux** [comment]
@Tyriar Just checked how c9 does their link matching, as it works pretty well. Here's how they do it, just if you're interested: [https://github.com/c9/core/blob/master/plugins/c9.ide.terminal/aceterm/hover_link.js](https://github.com/c9/core/blob/master/plugins/c9.ide.terminal/aceterm/hover_link.js)

**Comment by parisk** [comment]
@Tyriar I have my concerns about making Ctrl + Click the default behavior, since it's a non-standard.

I think that we should just expose the linkified element in some sort of event and let the consumer app manipulate it. So IMO just exposing the element to the handler should do the job.

**Comment by Tyriar** [comment]
@parisk you mean the event not the element?

**Comment by mofux** [comment]
The event would contain a reference to the element (evt.target), wouldn't it? I think a good reason for exposing the event would be the fact that it could be prevented (to stop it following the link on click for example)

**Comment by Tyriar** [comment]
@mofux yes it would, but also expose things like `MouseEvent.ctrlKey` so consumers can do ctrl key themselves.

**Comment by mofux** [comment]
@Tyriar perfect, and the href attribute of the element would probably equal the uri from the matcher?

**Comment by Tyriar** [comment]
The uri would need to be a param as well: `(event: MouseEvent, uri: string) => boolean` since only standard web links use `href`

**Comment by mofux** [comment]
Perfect, looks good to me.

**Comment by mofux** [comment]
What is the reason not to `href` for example `file://` uri's? I think opening the file locally when clicked and not prevent would be a good default.

**Comment by Tyriar** [comment]
Yes it allows a handler to override the hypertext logic.

**Pull request merged**
