### PR TITLE
Convert xterm.js to TypeScript!

### PR DESCRIPTION
**Pull request by Tyriar**
Part of #335

This PR does the following:

- Moves contents of xterm.js to Terminal.ts
- Expose entrypoint at xterm.ts
- Convert Terminal to a class
- Moved old 'static' `Terminal.member` to functions/variables scoped to file
- Replaced the majority of usages of `Terminal[optionsKey]` with `Terminal.options[optionsKey]`
- The type `any` is used in many places to get the conversion over with quickly, these can be refined later

Verification done:

Testing done in Chrome 51 and Firefox 50
- [x] npm test
- [x] ls -lR
- [x] Scrolling via mouse/keyboard
- [x] tmux input/split/scroll
- [x] vim input/scroll

### CODE REVIEW

**Comment by parisk** [comment]
Great! I got two proposals before moving on a full review:

1. We wait to merge all hanging PRs first, before dealing with this, since it's the biggest one.
2. Keep `xterm.ts` as `xterm.js` just for reference to the project's name. The syntax looks like it can stay exactly the same.

**Comment by Tyriar** [comment]
Sounds good, the line wrap PR is the main thing that needs to move before this to prevent some merge headaches.

**Comment by hsk** [comment]
Nice too meet you.
I worked without noticing pullrequest.
Please refer if you like.

https://github.com/hsk/xterm.js/blob/master/src/xterm.ts

This work difference strict types than your Convert.

**Comment by Tyriar** [comment]
@hsk the reason this wasn't merged is because it's a large diff and there were (and still are) community PRs out that would cause bit headaches for contributors. Pulling things out of xterm.js slowly is probably the better approach but probably not until https://github.com/sourcelair/xterm.js/pull/609 is merged

**Pull request closed without merging**
