### PR TITLE
Do not browserify xterm again inside search addon.

### PR DESCRIPTION
**Pull request by ficristo**

### CODE REVIEW

**Comment by Tyriar** [comment]
Hmm, even after this change it seems xterm.js is being pulled in to the search addon?

**Comment by Tyriar** [comment]
Ah, it's happening because https://github.com/sourcelair/xterm.js/pull/834 was merged. That's the reason I kept it separate; as it breaks the ./build/ output.

/cc @parisk @blink1073

**Comment by Tyriar** [comment]
Created https://github.com/sourcelair/xterm.js/issues/927 to discuss.

**Comment by ficristo** [comment]
It seems to work for me. The resulting search file drops from ~200KB to ~5KB.

If it's about v3, I think you need to change this:
`.external(path.join(outDir, 'xterm.js'))`
to this
`.external(path.join(outDir, 'Terminal.js'))`

**Comment by Tyriar** [comment]
Ah you're right, that was the problem 😄

**Comment by Tyriar** [comment]
I'll work on an adaption for `v3`

**Pull request merged**
