### PR TITLE
Fix cursor blinking when enabled

### LINKED ISSUE #119: Cursor blinking seems to be broken
Add option to demo:

```js
    term = new Terminal({
      cursorBlink: true
    })
```

Doesn't work

### PR DESCRIPTION
**Pull request by Tyriar**
Fixes #119

### CODE REVIEW

**Comment by parisk** [comment]
What about implementing this with CSS animations? Seems that browser support is pretty good: http://caniuse.com/#feat=css-animation.

**Comment by Tyriar** [comment]
Could be a nice improvement. Would be good to get this in to fix it though.

**Comment by parisk** [comment]
Are there any particular issues that prevent us from going with CSS animations within the scope of this PR?

**Comment by Tyriar** [comment]
Time was the only reason, I went ahead and did it though :stuck_out_tongue: 

It works fine when https://github.com/sourcelair/xterm.js/pull/133 is applied. It's actually quite convenient as refresh recreates the cursor which resets the cursor, so no need to manually reset it on keydown.

**Comment by parisk** [comment]
Thanks a lot @Tyriar

**Pull request merged**
